### ISSUE TITLE
Jungle2.0 push_transaction cors error?

### ISSUE THREAD

**Issue by gavinwyf** [EOS-Jungle-Testnet/Node-Installation#1]
Error:
Access to fetch at 'https://junglehistory.cryptolions.io/v1/chain/push_transaction' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Network:
const network = Network.fromJson({
    blockchain: 'eos',
    host: 'junglehistory.cryptolions.io',
    port: 443,
    protocol: 'https',
    chainId: 'e70aaab8997e1dfce58fbfac80cbbb8fecec7b99cf982a9444273cbc64c41473',
});

**Comment by ansigroup** [comment]
you don't need a history node to push transaction.. please use jungle2.cryptolions.io
