### ISSUE TITLE
How to stop this testnet?

### ISSUE THREAD

**Issue by Serg-Maximchuk** [EOS-Jungle-Testnet/Node-Installation#4]
I've being working with this testnet for some while, and now I'm about to move to real EOS, how can I stop running testnet? I've used auto installation on server, but I don't remember directory where wget was executed for installation...

**Comment by bublik77** [comment]
> I've being working with this testnet for some while, and now I'm about to move to real EOS, how can I stop running testnet? I've used auto installation on server, but I don't remember directory where wget was executed for installation...

Hi, please try to execute "ps aux | grep nodeos" and you see in the option --data-dir full path to your node directory

**Comment by Serg-Maximchuk** [comment]
Thank you!
